
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class deskwithshelvesAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new deskwithshelvesAddonDeed();
			}
		}

		[ Constructable ]
		public deskwithshelvesAddon()
		{



			AddComplexComponent( (BaseAddon) this, 3645, 1, 1, 0, 1192, -1, "desk with shelves", 1);// 1
			AddComplexComponent( (BaseAddon) this, 3645, -1, 1, 0, 1192, -1, "desk with shelves", 1);// 2
			AddComplexComponent( (BaseAddon) this, 3645, 1, 0, 0, 1192, -1, "desk with shelves", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3645, -1, 0, 0, 1192, -1, "desk with shelves", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3645, 1, 0, 3, 1192, -1, "desk with shelves", 1);// 5
			AddComplexComponent( (BaseAddon) this, 3645, 1, 1, 3, 1192, -1, "desk with shelves", 1);// 6
			AddComplexComponent( (BaseAddon) this, 3645, -1, 0, 3, 1192, -1, "desk with shelves", 1);// 7
			AddComplexComponent( (BaseAddon) this, 3645, -1, 1, 3, 1192, -1, "desk with shelves", 1);// 8
			AddComplexComponent( (BaseAddon) this, 10409, 1, 0, 8, 1, -1, "desk with shelves", 1);// 9
			AddComplexComponent( (BaseAddon) this, 10409, 1, 1, 8, 1, -1, "desk with shelves", 1);// 10
			AddComplexComponent( (BaseAddon) this, 10410, 0, 0, 8, 1, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 10411, -1, 0, 8, 1, -1, "desk with shelves", 1);// 12
			AddComplexComponent( (BaseAddon) this, 10410, 0, 1, 8, 1, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 10411, -1, 1, 8, 1, -1, "desk with shelves", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2717, 1, 0, 7, 1192, -1, "desk with shelves", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2717, 0, 0, 7, 1192, -1, "desk with shelves", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2717, -1, 0, 7, 1192, -1, "desk with shelves", 1);// 17

		}

		public deskwithshelvesAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class deskwithshelvesAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new deskwithshelvesAddon();
			}
		}

		[Constructable]
		public deskwithshelvesAddonDeed()
		{
			Name = "deskwithshelves";
		}

		public deskwithshelvesAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}
